<?php

/*
 * This in an intern container (Kernel container)
 * We need to run the kernel To set up some default variable.
 * Before to run the kernel, we need to initialize some generic classes.
 * The user can override keys. The files in the /config/ directory are the highest priority.
 * Do not edit this file you're going to break the framework!
 * If you want to edit the configuration, please use .env file or to edit files in the /config/ repository instead of
 *  this file.
 *
 * Thank you!
 */

use App\FlexibleFramework\Session\SessionFactory;
use FlexibleFramework\Router;
use FlexibleFramework\Session\SessionInterface;

use function DI\autowire;
use function DI\factory;

return [
    'project.dir' => dirname(__DIR__),
    'app.env' => getenv('APP_ENV') ?: 'prod',
    'session.driver' => 'php',
    SessionInterface::class => factory(SessionFactory::class),
    Router::class => autowire(),
];
